# Use root/example as user/password credentials
version: '3.8'
name: Sysmap-Parrot
services:

  backend: 
    container_name: backend
    #image: gahbr/parrot
    build:
      context: ./
    command: npm start
    ports: 
      - '3000:3000'
    volumes: 
      - .:/usr/app
    depends_on:
      - mongodb
      - minio
    environment:
      JWT_SECRET_KEY : sysmap
      MONGO_URI: mongodb://mongodb:27017/parrotdb
      MINIO_ENDPOINT : 192.168.1.7
      MINIO_PORT : 9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
   
  minio:
    container_name: minio
    image: minio/minio
    command: ["server", "--console-address", ":9001", "/data"]
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data

  createbuckets:
    container_name: create bucket
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/sysmap;
      /usr/bin/mc anonymous set public minio/sysmap;
      exit 0;
      "
volumes:
  minio_data:
   
   

